# Scraped from: https://wiki.multitheftauto.com/wiki/GetBrowserSettings
client:
  name: getBrowserSettings
  description: This function returns a table containing the browser settings.
  parameters: []
  examples:
  - path: examples/getBrowserSettings-1.lua
    description: This creates a browser and get the browser settings when the browser
      has been created
    side: client
  incomplete: true
