client:
  name: setDiscordApplicationID
  description: 'The function can assign your own application to use in Rich Presence.

    You can create an application **[here](https://discord.com/developers/applications)**'
  parameters:
  - name: applicationID
    type: string
    description: a [[string]] representing your Discord application's ID.
  examples:
  - path: examples/setDiscordApplicationID-1.lua
    description: This example outputs whether the application was successfully setup
      and sets a custom asset image.
  - path: examples/setDiscordApplicationID_OOP-1.lua
    description: This example outputs whether the application was successfully setup
      and sets a custom asset image.
    oop: true
  returns:
    values:
    - type: bool
      name: reset
    description: Returns **true** if function succeeds, **false** if the client has disabled
      rich presence.
  oop:
    element: discordrpc
    method: setApplication
    static: true
  notes:
  - type: info
    content: To reset the application ID, please use [[resetDiscordRichPresenceData]].
  - type: important
    content: In order for the function to work correctly, the user must have their
      activity privacy/status enabled in Discord.
  version:
    added: 1.6.0 r22270
