# Scraped from: https://wiki.multitheftauto.com/wiki/SetDiscordApplicationID
client:
  name: setDiscordApplicationID
  description: 'The function can assign your own application to use in Rich Presence.

    You can create an application **[here](https://discord.com/developers/applications)**'
  parameters: []
  examples:
  - path: examples/setDiscordApplicationID-1.lua
    description: This example outputs whether the application was successfully setup
      and sets a custom asset image.
    side: client
  notes:
  - type: important
    content: To reset the application ID, please use resetDiscordRichPresenceData
  - type: important
    content: In order for the function to work correctly, the user must have their
      activity privacy/status enabled in Discord.
